### ISSUE TITLE
Login node creation: mounts do not survive a reboot

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#104]
Software: Trinity * r3
74c8094
Component: Login node creation
Use Case: 3.2

After rebooting the login node, the mounts are gone. They should be created using fstab manipulation and not using mount commands.

**Comment by themisa** [comment]
[root@login ~]# cat /etc/fstab

#
# /etc/fstab
# Created by anaconda on Mon Dec  1 13:05:11 2014
#
# Accessible filesystems, by reference, are maintained under '/dev/disk'
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info
#
UUID=c2ca95b2-6cfd-4f33-be5b-59992d300ba9 /                       xfs     defaults        1 1
controller:/cluster /cluster nfs rsize=8192,wsize=8192,timeo=14,intr
controller:/trinity /trinity nfs rsize=8192,wsize=8192,timeo=14,intr
controller:/home /home nfs rsize=8192,wsize=8192,timeo=14,intr


Fixed in r3_login, needs to merge with r3

**Comment by themisa** [comment]
merged
