### ISSUE TITLE
Login node creation: no /cluster/apps and /cluster/modulefiles

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#185]
**version:** 618ba29

After creating the login node for vc-a, no apps and modulefiles directories were created.
```
[root@c001 ~]# ls /cluster
etc
```

**Comment by hansthen** [comment]
Did not check against vc-b yet.

**Comment by hansthen** [comment]
Workaround: create manually.

**Comment by abhimukh** [comment]
This is a duplicate of #148 and #167. Already fixed in b0d04ea

**Comment by abhimukh** [comment]
Further comment: The modulefiles and apps directories are created by the API server when HPC resources are added to the cluster for the first time. Since, the first resource allocation for vc-a is not done by the API server, the aforementioned directories are not created. 

The modulefiles and apps directories for vc-a should be in the repo (just like the /cluster/etc/vc-a/slurm directory).

**Comment by themisa** [comment]
to test this, need to reprovision controller.

**Comment by abhimukh** [comment]
This issue should be fixed now. Reassigning @themisa

**Comment by themisa** [comment]
[root@c001 /]# cat /etc/resolv.conf 
nameserver 10.141.255.254
search vc-b
[root@c001 /]# ls /cluster
apps  etc  modulefiles

**Comment by themisa** [comment]
* r3
f877aca
