### ISSUE TITLE
IMPI bug

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#204]
[root@controller mkfs]# rpower node001-node064 reset
Error: ipmi plugin bug, pid 2658, process description: 'xCATd SSL: rpower to node001-node064 for root@localhost: ipmi instance' with error 'Undefined subroutine &xCAT::IPMI::hmac_sha1 called at /opt/xcat/lib/perl/xCAT/IPMI.pm line 860.

**Comment by hansthen** [comment]
See: http://sourceforge.net/p/xcat/bugs/4341/

**Comment by hansthen** [comment]
workaround yum install perl-Digest-SHA1

**Comment by themisa** [comment]
[root@master trinity]# ./includes 59bf9ba
git merge-base --is-ancestor 59bf9ba 06c3594
not included

**Comment by themisa** [comment]
@hansthen this is not included in r3, and the milestone is set to M3

**Comment by themisa** [comment]
fixed in r3

[root@controller centos]# yum info perl-Digest-SHA1
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.cj2.nl
 * centosplus: mirror.cj2.nl
 * extras: ftp.nluug.nl
 * fasttrack: centos.mirror.transip.nl
 * updates: centos.mirror.transip.nl
Installed Packages
Name        : perl-Digest-SHA1
Arch        : x86_64
Version     : 2.13
Release     : 9.el7
Size        : 105 k
Repo        : installed
From repo   : anaconda
Summary     : Digest-SHA1 Perl module
URL         : http://search.cpan.org/dist/Digest-SHA1/
License     : GPL+ or Artistic
Description : The Digest::SHA1 module allows you to use the NIST SHA-1 message
            : digest algorithm from within Perl programs. The algorithm takes as
            : input a message of arbitrary length and produces as output a 160-bit
            : "fingerprint" or "message digest" of the input.
            : 
            : The Digest::SHA1 module provide a procedural interface for simple use,
            : as well as an object oriented interface that can handle messages of
            : arbitrary length and which can read files directly.
            : 
            : A binary digest will be 20 bytes long. A hex digest will be 40
            : characters long. A base64 digest will be 27 characters long.
