### ISSUE TITLE
trinity_api: node allocation shows nodes without a project

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#216]
If a node is allocated to a vc-\<group\>, without there being a project for that node, they will still show up in the allocation overview. This is a weird. The system should either not show these allocations or show that some nodes are allocated without a matching project.

**Comment by hansthen** [comment]
This can be avoided by either of the following 
1. creating a default project during installation
2. not manually allocating nodes to a vc-\<group\>. However, the trinity nodes will then not be runnable before the openstack node is created and configured.

**Comment by abhimukh** [comment]
@hansthen The culprit is vc-a! The number of allocated containers by hw group (shown in the pie charts) should match the number of allocated containers by cluster/tenant (shown in the data table). If we only show containers allocated to tenants, then the first time the dashboard is accessed, the pie charts will show that all the containers have already been allocated, but the data table will show zero allocations (all the containers are in vc-a, but not tenant 'a' yet). 

I prefer option (2) with some slight modifications.

2(a) We create an xCAT group 'container' and assign all the containers (c<nnn>) to it. Note that this group is called container and not vc-container
2(b) We removed trinity from the set of services that are started on boot.
2(c) The trinity service will be started/restarted during cluster partitioning/repartitioning.

**Comment by hansthen** [comment]
I do not understand the proposal. However, my main goal is the following:
1. Most of our customers will want a single partition (at least to start with).
2. I want to reduce the number of manual actions involved in getting to a running (default) state.
3. So the installation process should create a default tenant and allocate all resources to that tenant.
4. Especially, it should not be necessary for the engineer to login and create a tenant for the default partition.

Can we come up with a design that realizes this?

**Comment by abhimukh** [comment]
@hansthen In order for the containers to be added to the xCAT tables they must at least be a part of one nodegroup. Currently, this node group is vc-a, which causes all other adjustments in the code. We can get around this by adding them all to a group called _container_, i.e., they are created by not assigned to any virtual cluster. Note: we can also simply use _hw-GenericNodes_ (see discussion following #213 ).

However, this requires a more detailed design discussion (cf. kill vc-a)

**Comment by hansthen** [comment]
I think we decided to show these nodes with a warning.

**Comment by abhimukh** [comment]
@hansthen In r5, there is an extra column in HPC_overview. The VCs with no tenant are listed as "No Tenant" and the others are listed as "Active".

Reassigning to @themisa for testing

**Comment by themisa** [comment]
I think this is also closed by the decision taken in #231. We will always have a default cluster on installation . There is also the addition of the xtra column in HPC_overview as of r5
