### ISSUE TITLE
openstack installation: infinite loop

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#276]
**version:** * r3
0d12eb5

**hardware:** amaster, node003

openstack installation fails -- provisioning goes in a loop without getting to sshd stage.

Output from console:

dracut-initqueue[865]: the requested url returned error: 404 not found

**Comment by hansthen** [comment]
The dracut-initqueue message can be ignored. It points to an updates.img which does not have to be present on the installation medium.

The problem was caused by the openstack node not being able to reach the internet. This was because the IP tables on the controller node were not setup correctly. I have not yet found the cause for this. When we reinstall the controller we must test this again.

**Comment by themisa** [comment]
This was due to #281 . This is now fixed, which also fixes this problem!
