### ISSUE TITLE
colander: nfs-server dead

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#450]
**Version:** colander 22487d1
**Environment:** amaster

On controller-2 of amaster (active node) nfs-server not running, (so trinity_api fails to start on openstack node)

```
[root@controller-2(amaster) ~]# service nfs-server status
Redirecting to /bin/systemctl status  nfs-server.service
nfs-server.service - NFS server and services
   Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; enabled)
   Active: inactive (dead)

Sep 20 21:52:51 controller-2.cluster systemd[1]: Dependency failed for NFS server and services.
```

**Comment by Marc69** [comment]
[root@controller-2(amaster) ~]# service nfs-server status
Redirecting to /bin/systemctl status  nfs-server.service
nfs-server.service - NFS server and services
   Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; enabled)
   Active: active (exited) since di 2015-09-22 14:45:31 CEST; 1 day 22h ago
  Process: 11122 ExecStart=/usr/sbin/rpc.nfsd $RPCNFSDARGS (code=exited, status=0/SUCCESS)
  Process: 11071 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=0/SUCCESS)
 Main PID: 11122 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/nfs-server.service

**Comment by hansthen** [comment]
Tested against a manual adaptation of an older release.

**Comment by Marc69** [comment]
Works in r6 10cffc2:

[root@controller-1(amaster*) ~]# service nfs-server status
Redirecting to /bin/systemctl status  nfs-server.service
nfs-server.service - NFS server and services
   Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; disabled)
   Active: active (exited) since Mon 2015-10-26 12:01:25 CET; 2h 17min ago
  Process: 6530 ExecStart=/usr/sbin/rpc.nfsd $RPCNFSDARGS (code=exited, status=0/SUCCESS)
  Process: 6527 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=0/SUCCESS)
 Main PID: 6530 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/nfs-server.service

Oct 26 12:01:25 controller-1.cluster systemd[1]: Starting NFS server and ser....
Oct 26 12:01:25 controller-1.cluster systemd[1]: Started NFS server and serv....
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by Marc69** [comment]
... and in
**Version:** r6 aa08d39
**Environment:** amaster
[root@controller-2(amaster) ~]# service nfs-server status
Redirecting to /bin/systemctl status  nfs-server.service
nfs-server.service - NFS server and services
   Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; disabled)
   Active: active (exited) since Thu 2015-12-03 12:24:30 CET; 1h 2min ago
  Process: 4785 ExecStart=/usr/sbin/rpc.nfsd $RPCNFSDARGS (code=exited, status=0/SUCCESS)
  Process: 4782 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=0/SUCCESS)
 Main PID: 4785 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/nfs-server.service

Dec 03 12:24:29 controller-2.cluster systemd[1]: Starting NFS server and services...
Dec 03 12:24:30 controller-2.cluster systemd[1]: Started NFS server and services.
