### ISSUE TITLE
xCAT: node database should be updated to reflect only discovered nodes

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#48]
The xCAT database maintains info about all nodes added using nodeadd, whether they have been discovered or not. In principle, it is possible to extract the discovered nodes, but it is clumsy and requires more operations. It will be useful to have a script which cleans up the database after discovery.

And as a corollary,  when new nodes need to be added their names should automatically determined instead of having to browse the database.

**Comment by hansthen** [comment]
This report was introduced because we did not want to allocate non-functional nodes to a cluster.

A cleanup script will remove undiscovered nodes from the database, which will also hide those nodes from view. We want admins to check why those nodes did not get discovered. As discussed with Abhi, we can model "not being discovered discovery" as a special failure state and solve the issue using monitoring. 

So (non-functional) nodes can get allocated to a vc, but we will have monitoring point it out to us.
