### ISSUE TITLE
Cluster services are open on external interface

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#504]
>[bruno@edac ~]$ nmap -sV --version-all -p 53 10.1.182.204
(...)
PORT     STATE SERVICE     VERSION
22/tcp   open  ssh         OpenSSH 6.6.1 (protocol 2.0)
53/tcp   open  domain
80/tcp   open  http        Apache httpd 2.4.6 ((CentOS) OpenSSL/1.0.1e-fips)
111/tcp  open  rpcbind
389/tcp  open  ldap        OpenLDAP 2.2.X - 2.3.X
443/tcp  open  ssl/http    Apache httpd 2.4.6 ((CentOS) OpenSSL/1.0.1e-fips)
2049/tcp open  rpcbind
3001/tcp open  ssl/nessus?
5050/tcp open  tcpwrapped
7911/tcp open  omapi       ISC (BIND|DHCPD) OMAPI
8008/tcp open  http?

The whole cluster is open to public in its external interface which is not what you want obviously. Services open to the external interfaces should only be the ones necessary to access the cluster.

This is a major security issue if not dealt with properly and can lead to infrastructure conflicts in datacenters where a cluster is installed.

**Comment by hansthen** [comment]
As a temporary workaround, perform this:
```
[root@controller(unknown*) ~]# iptables -A INPUT -i enp2s0f0 -m state --state ESTABLISHED,RELATED -j ACCEPT
[root@controller(unknown*) ~]# iptables -A INPUT -i enp2s0f0 -p tcp --dport 22 -j ACCEPT
[root@controller(unknown*) ~]# iptables -A INPUT -i enp2s0f0 -j DROP
```

**Comment by hansthen** [comment]
For a more permanent solution activate the `cv_controller_firewall` postscript for the controller.

**Comment by brunopereira81** [comment]
Any good reasons not to add a shorewall to a the setup or even use the builtin `firewall` service to do these things? Bright uses shorewall and I have installed and configured it on several occasions for xCAT, `firewall` comes by default with RHEL7 derivatives and is very simple to setup.

We need something more simple and at the same time configurable than just `iptables`: if you are doing a complex configuration iptables can become complicated and not very efficient to use just by itself.

Customers will not find it very user friendly to use and documenting complex setups will be very hard and time consuming.

**Comment by hansthen** [comment]
Yes there are good reasons to not use `shorewall` or the `firewall` service. The reason is that openstack (and docker) manipulates iptable rules directly. Both `shorewall` and `firewall` have a simplified database that is used to generate iptable rules. This means that when restarted `shorewall` or `firewall` will overwrite hose the iptable rules which will make openstack stop functioning. 

Most openstack guides detailing openstack on RH based systems disable firewalld for this reason. 

However, in Trinity, the controller node is not meant to be a public facing system. We expect it to be shielded from general access and only to be used via ssh by administrators. This can be ensured either by a very restrictive host based firewall, but preferably by a dedicated firewall. So there should be no reason to setup complicated firewall rules on the controller.

The nodes that are accessible to the general public are the login nodes. There people can run whatever firewall tools they want.

**Comment by themisa** [comment]
**Version:** r6 1ecbf63
**Environment:** tmaster
*

[root@controller(tmaster) xcatpost]# ./cv_controller_firewall 
iptables: Saving firewall rules to /etc/sysconfig/iptables:[  OK  ]

```
[root@tmaster(tmaster) tables]# nmap node001

Starting Nmap 6.40 ( http://nmap.org ) at 2015-11-19 18:33 CET
Nmap scan report for node001 (192.168.1.1)
Host is up (0.00018s latency).
Not shown: 999 filtered ports
PORT   STATE SERVICE
22/tcp open  ssh
MAC Address: 0C:C4:7A:02:03:4C (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 4.76 seconds
```

**Comment by brunopereira81** [comment]
So you would be ok to have `shorewall` or `firewalld` in the controller and use a very restrictive iptables rule in the openstack node only for the login's from users to that node?

**Comment by hansthen** [comment]
In the R6 release we moved the openstack services to the controller so I would not expect it to work without glitches. If you have a configuration with a separate openstack and controller node you could theoretically install `firewalld` or `shorewall` yourself on the controller. It is just not a configuration that we test or support. 

However, the more important question is, why would anyone want to create very complicated firewall rules on the controller? The controller is not meant to be an edge system, we expect it to be on a secure network. We expose the virtual login nodes for this reason.

**Comment by brunopereira81** [comment]
> (...) why would anyone want to create very complicated firewall rules on the controller? The controller is not meant to be an edge system, we expect it to be on a secure network.

You controller is the gateway for your whole cluster network, it controls storage blocks and other devices, does health checks on those, sends emails in case something important gets broken, plus it stores your user homes which can (and probably will in a decent sized cluster) be stored in another remote filesystem. I find it very important from a sysadmin, and customer point of view to be able to setup a proper firewall in what is the gateway for a cluster.

What happens inside the openstack login nodes and the containers is not really that important until we can set up the whole environment from a host point of view.

**Comment by hansthen** [comment]
None of this requires that the controller be an edge system. It is not a gateway in any traditional sense of the word. We have a "proper firewall" on the controller (`iptables`). Your point was that you want to install a firewall management tool that is easy to use because you want to create complicated firewall rules. I do not see the need to create these complicated firewall rules.

**Comment by brunopereira81** [comment]
>  I do not see the need to create these complicated firewall rules.

Yes, that comes later with more and different cluster setups and installations.

The idea that the controller will still idle in a corner and not be used for much (not mention load, talking about functions) is not very realistic, customers can be very "creative" :)

You can do as you please with the ticket, don't see any further reasons to continue this discussion.
