### ISSUE TITLE
TERM env variable

### ISSUE THREAD

**Issue by dchirikov** [clustervision/trinity#516]
TERM variable needs to be seted up correctly in docker image.

**Comment by hansthen** [comment]
Why? We do not want users to ssh into the containers, but use slurm instead.

**Comment by dchirikov** [comment]
If we want to make it more user-friendly, decrease entry level of the Trinity, we should fix that. At least for diagnosis purposes if one suspects some issues on it, when you drain the node and cannot use slurm on it directly.

**Comment by hansthen** [comment]
It works correctly if users ssh into the container.
```
[hans@login ~]$ ssh c001.vc-a
Last login: Tue Dec  8 11:30:44 2015 from login-a.vc-a
[hans@c001 ~]$ echo $TERM
xterm
```
I understand that this does not work for the root user, as we disabled root login via ssh. We cannot just hard-code this into the container, as the TERM variable should be a function of the actual terminal used. Since we use `docker-enter` this means we need to find a way to have this program determine the TERM variable from the invoking process and export that back into the docker session.

**Comment by hansthen** [comment]
Something like this would do the trick.
```
     40     # Use env to clear all host environment variables and set then anew
     41     $LAZY_SUDO "$NSENTER" $OPTS env -i - $ENV TERM=$TERM $COMMAND
```

**Comment by themisa** [comment]
Fixed in:
**Version:** r7_login_image 660733d
**Environment:** tmaster

[root@c002 /]# echo $TERM
xterm
[root@c002 /]#
