### ISSUE TITLE
Trinity use hardcoded names for the container names

### ISSUE THREAD

**Issue by dchirikov** [clustervision/trinity#534]
For now the name of the container is being constructed by following line
```
NAME=$(hostname -s | sed s/node/c/)
```
So it is not possible  to add nodes with different names to the cluster. For instance gpu01.
Customer sometime wants to set their own naming scheme because of infrastructure requirements.

**Comment by hansthen** [comment]
This is by design. The proper way (in Trinity) of grouping nodes is by making them a member of the appropriate "hw-" group, e.g. hw-gpu. 

The problem with allowing custom naming schemes is that it is very easy to make it very complicated. E.g. do gpu01 and node001 point to the same node or different nodes? If so, how would we name the containers? Would we have to support nodes with multiple sections of digits, such as n01-01. What if a customers wants to name his physical nodes cNNN? 

To avoid all these problems in one fell swoop, it was decided to stick to a very simple and very rigid naming scheme. It is much easier to tell a customer "no, you cannot change the naming scheme" than "yes, you can but you cannot do X Y and Z, and oh I forgot, if you do Q or P it will sometimes break and it will cost me another week to set it up as you want it and test everything".

**Comment by dchirikov** [comment]
> gpu01 and node001 point to the same node or different nodes
Usualy it means `hostname=gpu01` and `hostname=node01`. See no issues here. Different.
>  very easy to make it very complicated. 
It is considered that Trinity was not being developed to say customers that they are working improperly before.
If customer already have a naming policy Trinity should follow infrastructure rules. "node01-003", or "tpc324-08". It should support it. Trinity can only _recommend_ use naming scheme.
regarding "gpu", "storage", "node" - it s natural to name nodes relevant the role.
