### ISSUE TITLE
MTU values of interfaces do not match

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#538]
The nodes in trinity use 9000 as a MTU and some other interfaces are the set the same. Others are set at 1500 MTU.

This should be cleaned and set to a default (1500 MTU works just fine all over the place) and let the engineer decide if it needs some sort of adjustment.

**Comment by hansthen** [comment]
I have changed this so the MTU is left at the default value.

**Comment by themisa** [comment]
no ip command on login node. cannot test

**Comment by themisa** [comment]
Fixed in:

**Version:** r7_login_image 14a418e
**Environment:** dmaster

on container: MTU 1500 (8: eth1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN)

on node: 2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000

on controller: : eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 100

on login node: 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000

So now it is consistent.
