### ISSUE TITLE
compute nodes cannot access internet (iptables not configured correctly)

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#56]
**Software:** Trinity
**Component of software:** 
**Hardware used:** controller03--> node03, node04 
**Test case**: 1.2.3 Compute nodes can connect to the internet
**Bug description:** could not connect to internet from nodes set by controller03
**Steps to reproduce bug:**
1) ssh controller03
2)ssh node03
3) ping google.com
**Expected output**:
<PING google.com (64.233.166.101) 56(84) bytes of data.
64 bytes from 64.233.166.101: icmp_seq=1 ttl=45 time=10.0 ms
64 bytes from 64.233.166.101: icmp_seq=2 ttl=45 time=40.6 ms
64 bytes from 64.233.166.101: icmp_seq=3 ttl=45 time=10.3 ms>

**Actual output:**
No route to host

**Comment by themisa** [comment]
<[root@controller ~]# iptables-save
# Generated by iptables-save v1.4.21 on Thu Feb 12 14:45:21 2015
*nat
:PREROUTING ACCEPT [4581:1704019]
:INPUT ACCEPT [1228:111287]
:OUTPUT ACCEPT [12637:651158]
:POSTROUTING ACCEPT [12637:651158]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
COMMIT
# Completed on Thu Feb 12 14:45:21 2015
# Generated by iptables-save v1.4.21 on Thu Feb 12 14:45:21 2015
*filter
:INPUT ACCEPT [635790:70897804]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [259879:2922735245]
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
COMMIT
# Completed on Thu Feb 12 14:45:21 2015>

**Comment by hansthen** [comment]
Theory: maybe the docker installation removes the old nat rules.

**Comment by hansthen** [comment]
This bug is still open:
[root@controller ~]# iptables-save
# Generated by iptables-save v1.4.21 on Mon Mar  2 15:49:40 2015
*nat
:PREROUTING ACCEPT [555:34424]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [141:8566]
:POSTROUTING ACCEPT [110:6600]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -o eno1 -j MASQUERADE
COMMIT
# Completed on Mon Mar  2 15:49:40 2015
# Generated by iptables-save v1.4.21 on Mon Mar  2 15:49:40 2015
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [81214:243741248]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
**-A FORWARD -j REJECT --reject-with icmp-host-prohibited**
-A FORWARD -i eno2 -j ACCEPT
COMMIT
# Completed on Mon Mar  2 15:49:40 2015

[root@controller ~]# iptables-save
# Generated by iptables-save v1.4.21 on Mon Mar  2 15:57:32 2015
*nat
:PREROUTING ACCEPT [580:36134]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [148:8986]
:POSTROUTING ACCEPT [116:6960]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -o eno1 -j MASQUERADE
COMMIT
# Completed on Mon Mar  2 15:57:32 2015
# Generated by iptables-save v1.4.21 on Mon Mar  2 15:57:32 2015
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [3:252]
:OUTPUT ACCEPT [301:31713]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -i eno2 -j ACCEPT
COMMIT
# Completed on Mon Mar  2 15:57:32 2015

**Comment by hansthen** [comment]
It is unclear which part of the installation adds this part.

**Comment by brunopereira81** [comment]
Check before and after docker packages install? Seems like to be a bridge configuration for docker, can you check if any docker packages adds iptables rules to the system?

Had a customer breaking the network after installing docker with shorewall active.

**Comment by themisa** [comment]
This is on controller02 (xcat controller)

[root@controller ~]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     icmp --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:ssh
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited
ACCEPT     all  --  anywhere             anywhere

**Comment by hansthen** [comment]
Since it is unclear what the cause of the error is, we can go forward using a workaround. After installing the controller execute these commands:

```
iptables-save
iptables -D FORWARD 4
```

**Comment by hansthen** [comment]
a208b25 did not work.

**Comment by themisa** [comment]
it seems to work: for * r3
13ff36c

[root@controller xcatpost]# iptables-save
# Generated by iptables-save v1.4.21 on Tue Mar 10 17:04:02 2015
*nat
:PREROUTING ACCEPT [661:41648]
:INPUT ACCEPT [2:148]
:OUTPUT ACCEPT [173:10535]
:POSTROUTING ACCEPT [129:7760]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -o eno1 -j MASQUERADE
COMMIT
# Completed on Tue Mar 10 17:04:02 2015
# Generated by iptables-save v1.4.21 on Tue Mar 10 17:04:02 2015
*filter
:INPUT ACCEPT [1662:230203]
:FORWARD ACCEPT [56:4256]
:OUTPUT ACCEPT [97097:301257796]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -i eno2 -j ACCEPT
COMMIT
# Completed on Tue Mar 10 17:04:02 2015

**Comment by hansthen** [comment]
QA verified?

**Comment by themisa** [comment]
* r3
74c8094

fixed. iptables on controller correct. nodes can access internet on netboot without further tweaking
