### ISSUE TITLE
DNS misconfiguration after network restart

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#587]
After installation DNS resolving seems to be pointing only to external interfaces, no internal addresses can be resolved

```
[root@controller(150280*) ~]# host switch
Host switch not found: 3(NXDOMAIN)
[root@controller(150280*) ~]# host node001
Host node001 not found: 3(NXDOMAIN)
```

Configuration seems correct:

```
[root@controller(150280*) ~]# tabdump site
#key,value,comments,disable
"domain","cluster",,
"installdir","/install",,
"master","10.141.255.254",,
"forwarders","8.8.8.8,8.8.4.4",,
"nameservers","<xcatmaster>",,
"tftpdir","/tftpboot",,
"xcatdport","3001",,
"xcatiport","3002",,
"xcatconfdir","/etc/xcat",,
"timezone","UTC",,
"dhcpinterfaces","eno2",,
"dnsinterfaces","br100",,
```

But our `resolv.conf` file is populated wrongly:

```
[root@controller(150280*) ~]# cat /etc/resolv.conf 
; generated by /usr/sbin/dhclient-script
search clustervision.com. cluster
nameserver 10.1.199.6
nameserver 10.1.199.4
nameserver 10.1.199.5
```

Possibly due to the wrong entries in the external interface script file:

```
[root@controller(150280*) ~]# cat /etc/sysconfig/network-scripts/ifcfg-eno1 
# Generated by parse-kickstart
DEVICE=eno1
IPV6INIT=yes
BOOTPROTO=dhcp
UUID=ef9d06f4-4186-4510-a724-e5f16bf5348f
ONBOOT=yes
TYPE=Ethernet
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
NAME="System eno1"
PEERDNS=yes
PEERROUTES=yes
IPV6_PEERDNS=yes
IPV6_PEERROUTES=yes
```

[version]
* r7
85ff0e9

**Comment by hansthen** [comment]
You should use `host node001 localhost`. Sorry for the confusion. The xCAT controller is not configured to use itself as a nameserver. We want it to point to the client's nameserver for DNS resolving (and we use DHCP to determine what the nameserver is). Since xCAT requires that the local DNS server entries are duplicated in /etc/hosts, this is not be a problem. The reason for using an external nameserver, is that we can then use DNS names for e.g. the company LDAP server. 

I know that we can also use DNS forwarding for this, but in terms of procedures, this is more complicated to automate. E.g. how would we configure the external DNS server during controller installation automatically?

**Comment by Marc69** [comment]
**Version:** r8 1b911a6
**Environment:** amaster
```
[root@controller-1(amaster*) ~]# host node001 localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

node001.cluster has address 10.141.0.1
```
