### ISSUE TITLE
cv_install_openstack problems: no openstack services

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#66]
**Software:** Trinity r3 433cd3f

**Component:** install openstack
**Hardware:** SM4, controller02
**Test case:** install openstack
**Bug description:** after setting openstack image, there is no keystonerc_admin file, and none of the openstack services are running, even though the postinstall log file reports the openstack installation as finished
**Steps to reproduce:**
nodeset controller02 osimage=centos7.0-x86_64-install-openstack
rpower controller02 reset

wait until /var/log/postinstall.log reports
cat /var/log/postinstall.log
openstack installation finished
slapd installed
xcat installed
docker installed

**Expected output:**
in ~ there should be a keystonerc_admin, keystonerc_demo files
top should show openstack services runnin (nova, cinder, keystone etc)
**actual output:**
None of the above. also cannot find any conf files in /etc (eg etc/nova )

**Comment by hansthen** [comment]
In /var/log/xcat/xcat.log:

Complete!
ERROR:root:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/packstack/installer/run_setup.py", line 898, in main
    initPluginsConfig()
  File "/usr/lib/python2.7/site-packages/packstack/installer/run_setup.py", line 880, in initPluginsConfig
    plugin.initConfig(controller)
  File "/usr/lib/python2.7/site-packages/packstack/plugins/prescript_000.py", line 27, in initConfig
    default_ssh_key = os.path.join(os.environ["HOME"], ".ssh/*.pub")
  File "/usr/lib64/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'HOME'


^[[0;31mERROR : 'HOME'^[[0m
Traceback (most recent call last):
  File "/usr/bin/packstack", line 15, in <module>
    run_setup.main()
  File "/usr/lib/python2.7/site-packages/packstack/installer/run_setup.py", line 970, in main
    print output_messages.ERR_CHECK_LOG_FILE_FOR_MORE_INFO%(logFile)

This is a regression of an earlier error. Since we do not run packstack interactiverly, we should set HOME to /root.

**Comment by hansthen** [comment]
I adapted the file. Not fully tested yet.

**Comment by themisa** [comment]
Tested on controller02(SM), version 26af0dd
works. 
[root@openstack ~]# ls
anaconda-ks.cfg  Desktop  keystonerc_admin  keystonerc_demo

top reveals OS services running, and can fire up horizon dashboard
