### ISSUE TITLE
configured nodes become unreachable every morning

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#67]
**Software:** Trinity r3
**Component:** nodeset images
**Hardware:** Supermicro, Dell PowerEdge
**Test case:** general
**Bug description:**
We have been consistently noticing that nodes that have been nodeset either with controller, openstack, compute, trinity images become unpingable the next day and need a power reset, and sometimes a second nodeset. We should keep track of these incidents, and check whether it is "human error" related (people powering down nodes at night) or if the system is unstable.

**Comment by hansthen** [comment]
Tonight controller02 showed the problem. Tonight I will set a trace from master when it actually goes down: ping controller02 | while read pong; do echo "$(date): $pong"; done > /var/log/controller02.log

**Comment by hansthen** [comment]
In the log files on controller I see the following:
Feb 20 05:59:50 controller avahi-daemon[788]: Withdrawing address record for 192.168.1.2 on eno1.
Feb 20 05:59:50 controller avahi-daemon[788]: Leaving mDNS multicast group on interface eno1.IPv4 with address 192.168.1.2.
Feb 20 05:59:50 controller avahi-daemon[788]: Interface eno1.IPv4 no longer relevant for mDNS.
Feb 20 05:59:52 controller ntpd[12860]: Deleting interface #3 eno1, 192.168.1.2#123, interface stats: received=0, sent=0, dropped=0, active_time=42862 secs

**Comment by hansthen** [comment]
Turns out it makes no sense to have avahi-daemon running on our controller. It is some type of dynamic discovery protocol that makes sense for laptops, but hardly for us. I have disabled it for all the fixed install scripts and netboot images. Assigning to Themis for retesting.

**Comment by hansthen** [comment]
Assigned to themis for retesting.

**Comment by themisa** [comment]
Problem occured again today: 24/2 for version :
* r3
26af0dd

**Comment by brunopereira81** [comment]
Have a look at your DHCP leases and DHCP requests from the nodes, this seems to be that the nodes try to renew their addresses and the DHCP server is dead or not replying.

**Comment by hansthen** [comment]
The timeframe would be right, since it is half a day after initial boot. I will investigate.

**Comment by hansthen** [comment]
Looked at this type of message (on master) but no such messages at ca Feb 24 03:51.
[ 9667.776306] igb: eno2 NIC Link is Down
[ 9671.786229] igb: eno2 NIC Link is Up 100 Mbps Full Duplex, Flow Control: RX
[ 9744.584265] igb: eno2 NIC Link is Down
[ 9747.903725] igb: eno2 NIC Link is Up 100 Mbps Full Duplex, Flow Control: RX
[11881.139877] igb: eno2 NIC Link is Down
[11884.587385] igb: eno2 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[11885.372575] igb: eno2 NIC Link is Down
[11889.114388] igb: eno2 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[11890.398844] igb: eno2 NIC Link is Down
[11899.450036] igb: eno2 NIC Link is Up 100 Mbps Full Duplex, Flow Control: RX
[11899.450171] IPv6: ADDRCONF(NETDEV_CHANGE): eno2: link becomes ready

**Comment by hansthen** [comment]
Turned NetworkManager back on to see if that makes a difference.

**Comment by themisa** [comment]
openstack node (controller01) unreachable this morning, but that has to have Network manager off.
xCAT controller (controller02) fine (NetworkManager on)

**Comment by linuxstudio** [comment]
Seems to be a problem with the dhcp server on the master.
Looking at /var/lib/dhcpd/dhcpd.leases we can find duplicate entries for controller02, some of which have the form: 

host controller02 {
  dynamic;
  deleted;
}

There is only one entry for controller01 though. 
If you disabled NetworkManager on controller01 we should expect the same behaviour for that node (i.e. finding the deleted entry tomorrow).

Not sure which process is in charge of handling that file on the master. 

You may also want to have a look at:

[root@master ~]# diff /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.xcatbak

**Comment by hansthen** [comment]
These are created by xCAT. I think they are created when we do a rmnodecfg, during discovery and when we do a nodeset.

**Comment by linuxstudio** [comment]
Found this log entry on the master:

Feb 25 00:03:05 master dhcpd: DHCPREQUEST for 192.168.1.1 from b8:ca:3a:f9:6f:3f via eno2
Feb 25 00:03:05 master dhcpd: DHCPACK on 192.168.1.1 to b8:ca:3a:f9:6f:3f via eno2
Feb 25 00:03:04 openstack NetworkManager: Error: could not connect to NetworkManager DBus socket: (org.freedesktop.DBus.Error.NoServer) Failed to connect to socket /var/run/NetworkManager/private-dhcp: Connection refused 
Feb 25 00:03:04 openstack NetworkManager: Fatal error occured, killing dhclient instance with pid 2946.

So if NetworkManager is not running, the CGroup with the same name (NetworkManager) kills the other processess belonging to the same CGroup (the dhclient).

On controller01 we have:

[root@openstack ~]# systemctl status NetworkManager.service
NetworkManager.service - Network Manager
   Loaded: loaded (/usr/lib/systemd/system/NetworkManager.service; disabled)
   Active: inactive (dead) since wo 2015-02-25 11:24:56 CET; 4h 22min ago
 Main PID: 1907 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/NetworkManager.service
           └─3155 /sbin/dhclient -d -sf /usr/libexec/nm-dhcp-helper -pf /var/run/dhclient-em1.pid...

after a few hours, running the same command again on controller01 gives no running dhclient process:

[root@openstack ~]# systemctl status NetworkManager.service
NetworkManager.service - Network Manager
   Loaded: loaded (/usr/lib/systemd/system/NetworkManager.service; disabled)
   Active: inactive (dead) since wo 2015-02-25 11:24:56 CET; 5h 33min ago
 Main PID: 1907 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/NetworkManager.service

feb 25 11:24:56 openstack.cluster NetworkManager[1907]: <info> (em3): device state change: unavailable -> unmanaged (reason 'removed...10 36]
feb 25 11:24:56 openstack.cluster NetworkManager[1907]: <info> (em4): device state change: unavailable -> unmanaged (reason 'removed...10 36]
feb 25 11:24:56 openstack.cluster NetworkManager[1907]: <info> exiting (success)
feb 25 11:24:56 openstack.cluster systemd[1]: Stopped Network Manager.
feb 25 16:06:07 openstack.cluster dhclient[3155]: DHCPREQUEST on em1 to 192.168.1.254 port 67 (xid=0x1e39d639)
feb 25 16:06:07 openstack.cluster NetworkManager[1907]: DHCPREQUEST on em1 to 192.168.1.254 port 67 (xid=0x1e39d639)
feb 25 16:06:07 openstack.cluster dhclient[3155]: DHCPACK from 192.168.1.254 (xid=0x1e39d639)
feb 25 16:06:07 openstack.cluster NetworkManager[1907]: DHCPACK from 192.168.1.254 (xid=0x1e39d639)
feb 25 16:06:07 openstack.cluster NetworkManager[1907]: Error: could not connect to NetworkManager DBus socket: (org.freedesktop.DBu...efused
feb 25 16:06:07 openstack.cluster NetworkManager[1907]: Fatal error occured, killing dhclient instance with pid 3155.
Hint: Some lines were ellipsized, use -l to show in full.

So I would expect that when the dhcp lease expires (say, in half a day?) we will loose connection to controller01.

**Comment by brunopereira81** [comment]
You need to start configuring some sort of fixed addresses at least for the
controller nodes, from what I see these are using dhcp?

**Comment by linuxstudio** [comment]
I fully agree with https://github.com/brunopereira81[Bruno]

**Comment by hansthen** [comment]
I do not agree. We should be able to run xCAT controlled nodes with dhcp.

**Comment by linuxstudio** [comment]
according to the [documentation](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/ch-Configure_IP_Networking.html#sec-When_to_Use_Dynamic_Interface_Settings)

"NetworkManager will by default call the DHCP client, dhclient, when a profile has been set to obtain addresses automatically, or when an interface configuration file has BOOTPROTO set to dhcp. Where DHCP is required, an instance of dhclient is started for every Internet protocol, IPv4 and IPv6, on an interface. Where NetworkManager is not running, or not managing an interface, then the legacy network service will call instances of dhclient as required"

The problem here is that the legacy network service is in state failed:

[root@openstack ~]# systemctl status network.service -l
network.service - LSB: Bring up/down networking
   Loaded: loaded (/etc/rc.d/init.d/network)
   Active: failed (Result: exit-code) since Wed 2015-02-25 11:24:39 CET; 7h ago

Feb 25 11:24:38 openstack.cluster network[1973]: Bringing up loopback interface:  Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Feb 25 11:24:38 openstack.cluster network[1973]: Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Feb 25 11:24:39 openstack.cluster network[1973]: Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Feb 25 11:24:39 openstack.cluster network[1973]: Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Feb 25 11:24:39 openstack.cluster network[1973]: [  OK  ]
Feb 25 11:24:39 openstack.cluster network[1973]: Bringing up interface em1:  Error: Connection activation failed: Connection 'System em1' is not available on the device em1 at this time.
Feb 25 11:24:39 openstack.cluster network[1973]: [FAILED]
Feb 25 11:24:39 openstack.cluster systemd[1]: network.service: control process exited, code=exited status=1
Feb 25 11:24:39 openstack.cluster systemd[1]: Failed to start LSB: Bring up/down networking.
Feb 25 11:24:39 openstack.cluster systemd[1]: Unit network.service entered failed state.

so it won't start the dhcp client.

**Comment by linuxstudio** [comment]
giving the network.service a restart makes the thing work:

[root@openstack ~]# systemctl restart network.service 
[root@openstack ~]# systemctl status network.service -l
network.service - LSB: Bring up/down networking
   Loaded: loaded (/etc/rc.d/init.d/network)
   Active: active (running) since Wed 2015-02-25 18:36:50 CET; 8s ago
  Process: 2764 ExecStart=/etc/rc.d/init.d/network start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/network.service
           └─2971 /sbin/dhclient -H openstack -1 -q -lf /var/lib/dhclient/dhclient-c0bf5f83-1db8-44bd-82e4-e019ec62a08b-em1.lease -pf /var/run/dhclient-em1.pid em1

Feb 25 18:36:50 openstack.cluster network[2764]: RTNETLINK answers: File exists
Feb 25 18:36:50 openstack.cluster network[2764]: RTNETLINK answers: File exists
Feb 25 18:36:50 openstack.cluster network[2764]: RTNETLINK answers: File exists
Feb 25 18:36:50 openstack.cluster network[2764]: RTNETLINK answers: File exists
Feb 25 18:36:50 openstack.cluster network[2764]: RTNETLINK answers: File exists
Feb 25 18:36:50 openstack.cluster network[2764]: RTNETLINK answers: File exists
Feb 25 18:36:50 openstack.cluster network[2764]: RTNETLINK answers: File exists
Feb 25 18:36:50 openstack.cluster network[2764]: RTNETLINK answers: File exists
Feb 25 18:36:50 openstack.cluster network[2764]: RTNETLINK answers: File exists
Feb 25 18:36:50 openstack.cluster systemd[1]: Started LSB: Bring up/down networking.


Question is why it fails to start in the first place? It seems to complain about unable to read the /etc/sysconfig/network-scripts/ifcfg-lo file. Is that file missing in the original image (and maybe created by NetworkManager before you disable it)?

**Comment by brunopereira81** [comment]
I don't understand how things are built here. From what I understand there
is master node that deploys a controller node for openstack and nova
compute nodes. Should the controller not be the dhcp server from there on?

If you use rmnodecfg to remove a deployed controller it will remove the mac
from the mac table, the current chain from the chain and the entries from
the dhcp and DNS server in the bode that was used to deploy controller, so
its normal that if you do that the entry shows deleted in the lease file
and the controller cannot renew its IP address and kills dhclient.

Just guessing here, would need to have some more information to be able to
help, but this seems clearly a broken chain in the deployment process.

**Comment by hansthen** [comment]
@linuxstudio

I just did some testing on the Dell2 machine. As noted earlier, stopping the NetworkManager does not stop the dhcpclient. It looks like this also prevents the legacy network service to be started. If I kill the dhcpclient, and then start legacy network it works out okay. Shall we test that setup over the weekend?

**Comment by linuxstudio** [comment]
Fine for me testing that setup over the weekend.

**Comment by hansthen** [comment]
The trinity nodes seem to suffer from the same problem. This is a bit weird as we do not disable NetworkManager on the trinity nodes. Needs additional testing to see if this is exactly the same problem.

**Comment by brunopereira81** [comment]
I think are seeing this wrong: its not that the nodes are not requesting a new IP address from the DHCP server, it is that the DHCP server never returns a valid address to the node and the node ends up stopping requesting the address and the whole services get scrambled.

Where are the logs (dhcp requests are under /var/log/messages) for the same time in the node that is acting as DHCP server, does that node ever get the DHCP request from the trinity nodes? You should be able to see the request there.

Also @hansthen says he can see this in the master node (is that the node running the DHCP server?):

`[11884.587385] igb: eno2 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[11885.372575] igb: eno2 NIC Link is Down
[11889.114388] igb: eno2 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[11890.398844] igb: eno2 NIC Link is Down
[11899.450036] igb: eno2 NIC Link is Up 100 Mbps Full Duplex, Flow Control: RX`

Why would that interface be toggling rates between 100Mbps and 1000Mbps? That should be seen asap.

**Comment by linuxstudio** [comment]
controller03 that was installed by me and Jakub on friday is still reachable as of today:

[root@controller ~]# uptime
 15:05:54 up 3 days, 22:02,  1 user,  load average: 0,00, 0,01, 0,05
[root@controller ~]# systemctl status network.service
network.service - LSB: Bring up/down networking
   Loaded: loaded (/etc/rc.d/init.d/network)
   Active: active (running) since ma 2015-03-02 18:15:03 CET; 20h ago
  Process: 8986 ExecStart=/etc/rc.d/init.d/network start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/network.service
           └─9183 /sbin/dhclient -H controller -1 -q -lf /var/lib/dhclient/dhclient-d436a4a1-888e-43ab-bcaf-f23f6657f...

mrt 02 23:08:19 controller.cluster dhclient[9183]: bound to 192.168.1.3 -- renewal in 19013 seconds.
mrt 03 04:25:12 controller.cluster dhclient[9183]: DHCPREQUEST on em1 to 192.168.1.254 port 67 (xid=0x61cb1a2c)
mrt 03 04:25:12 controller.cluster dhclient[9183]: DHCPACK from 192.168.1.254 (xid=0x61cb1a2c)
mrt 03 04:25:14 controller.cluster dhclient[9183]: bound to 192.168.1.3 -- renewal in 19373 seconds.
mrt 03 09:48:07 controller.cluster dhclient[9183]: DHCPREQUEST on em1 to 192.168.1.254 port 67 (xid=0x61cb1a2c)
mrt 03 09:48:07 controller.cluster dhclient[9183]: DHCPACK from 192.168.1.254 (xid=0x61cb1a2c)
mrt 03 09:48:10 controller.cluster dhclient[9183]: bound to 192.168.1.3 -- renewal in 17822 seconds.
mrt 03 14:45:12 controller.cluster dhclient[9183]: DHCPREQUEST on em1 to 192.168.1.254 port 67 (xid=0x61cb1a2c)
mrt 03 14:45:12 controller.cluster dhclient[9183]: DHCPACK from 192.168.1.254 (xid=0x61cb1a2c)
mrt 03 14:45:14 controller.cluster dhclient[9183]: bound to 192.168.1.3 -- renewal in 19737 seconds.


What was basically done is:

1) acknowledge that NetworkManager.service was stopped and disabled
2) acknowledge that a dhclient process was still running as child of the CGroup of the stopped/disabled NetworkManager.service 
3) acknowledge that the network.service could not be started because there is already an instance of the dhclient running
4) kill the dhclient process
5) restart network.service with the command "sysctl restart network.service"

The node controller03 is still up and reachable and without NetworkManager running since already 3 days. So this manual trick seems to fix the issue.
We now have to see how to automate it properly, since the workaround implemented by Hans in commit e65c4b1 doesn't seem to be effective (I assume so, due to the last comment from Hans about the trinity nodes suffering of the same issue).

**Comment by hansthen** [comment]
The workaround seems to work for nodes running OpenStack. However, the trinity nodes (as far as I can remember) did not have NetworkManager disabled. I will split this into a separate issue.

**Comment by themisa** [comment]
fixed in * r3
5cead59

up for 3 days
