### ISSUE TITLE
Master installer: xCAT tables are not installed on controller

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#68]
[root@controller ~]# tabdump hosts
#node,ip,hostnames,otherinterfaces,comments,disable

**Comment by hansthen** [comment]
Is caused by reorganizing the file structure in the master_installer branch.
Files were copied from master:/trinity/xcat/tables. This has become master:/trinity/controller/xcat/tables.

**Comment by themisa** [comment]
Fixed by cb242d7
[root@controller ~]# tabdump hosts
#node,ip,hostnames,otherinterfaces,comments,disable
"compute","|\D+(\d+)$|10.141.((($1-1)/255)).(($1-1)%255+1)|","|\D+(\d+)$|node($1)|","|\D+(\d+)$|node($1)-bmc:10.148.((($1-1)/255)).(($1-1)%255+1),node($1)-ib:10.149.((($1-1)/255)).(($1-1)%255+1)|",,
"switch","10.141.253.1","switch",,,
"controller","10.141.255.254","controller",,,
"vc-a","|\D+(\d+)$|172.16.((($1-1)/255)).(($1-1)%255+1)|","|\D+(\d+)$|c($1)|",,,


[root@controller ~]# tabdump site
#key,value,comments,disable
"domain","cluster",,
"installdir","/install",,
"master","10.141.255.254",,
"forwarders","8.8.8.8,8.8.4.4",,
"nameservers","<xcatmaster>",,
"tftpdir","/tftpboot",,
"xcatdport","3001",,
"xcatiport","3002",,
"xcatconfdir","/etc/xcat",,
"timezone","Europe/Amsterdam",,
"dhcpinterfaces","eno2",,
